### ISSUE TITLE
URL Encode space to + (not %20)

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#1014]
@Rafiot This is spun out from https://github.com/MISP/MISP/issues/9033 where @iglocska fixed an issue by encoding strings with spaces to use `+` (not `%20`).

I've tested `get_organisation` and with the caller using the `+` the problem does not occur. We detected this only in that function, but it may affect others.

Test case:
```
(Pdb) misp.get_organisation('foo bar')
*** requests.exceptions.TooManyRedirects: Exceeded 30 redirects.
(Pdb) misp.get_organisation('foo+bar')
Something went wrong (404): {'name': 'Invalid organisation', 'message': 'Invalid organisation', 'url': '/organisations/view/foo+bar'}
{'errors': (404, {'name': 'Invalid organisation', 'message': 'Invalid organisation', 'url': '/organisations/view/foo+bar'})}
(Pdb) 
```

**Comment by Rafiot** [comment]
It probably means using [urllib.parse.quote_plus](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote_plus) in [_prepare_requests](https://github.com/MISP/PyMISP/blob/main/pymisp/api.py#L3701), instead of following the spec and letting requests encode the URL path normally.

I'm worried it will have really bad side effects.

**Comment by Rafiot** [comment]
That seems to be working.
