### ISSUE TITLE
Automation - How can I get Event information using the event id?

### ISSUE THREAD

**Issue by nalzaid** [MISP/PyMISP#290]
Hi, 

I am in the process of retrieving attributes information from the MISP(I queried the MISP and I used a curl command to get all the attributes that matches the searched query). 

I want to get the event information from which this attribute belongs. I have the event ID of each attribute, how can I fetch then event information through this eventid? 

(P.S. I tried to make another curl command for the events to get the event information; it worked but it is too slow! because it was inside a loop of all the attributes)

**Comment by winklerrr** [comment]
I think, the `get_event(event_id)` function in [`api.py`](https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L330) is what you are looking for.
You can check how the function retrieves the event data and then build your curl command accordingly:

`url = urljoin(self.root_url, 'events/{}'.format(event_id))`

If you work with Python just `import requests` module instead of using curl or just `import pymisp` for full api access.

**Comment by Rafiot** [comment]
yes, exactly :)

**Comment by Rafiot** [comment]
yes, exactly, thank you for the answer :)
