### ISSUE TITLE
Object to Object add_reference does not seem to work

### ISSUE THREAD

**Issue by eCrimeLabs** [MISP/PyMISP#319]
When creating two objects in MISP I attempted to add a reference between the two objects with the below code however it does not seem to work

Version: 
```
python3 -c "import pymisp; print(pymisp.__version__)"
2.4.99
```

Line adding the reference:
```
misp_object.add_reference(referenced_uuid=vt_obj_uuid, relationship_type='analysed-with', comment='Expanded with virustotal data')
```

I'm not getting any errors and the code for adding the two objects also works perfect, besides the missing relation :)

The full source code where it is use is here:
https://github.com/eCrimeLabs/vt2misp

The misp_object.add_reference is located at line 102

**Comment by Rafiot** [comment]
so that's because of a limitation in the data model. There are 2 ways to push references:
* Pushing the full event, with all the objects and references: objects need to be created with `standalone=False` when initialized
* Pushing objects one after the other, then the reference 

In your case, option 1 is probably the easiest: https://github.com/eCrimeLabs/vt2misp/blob/master/vt2misp.py#L70 => add `standalone=False`

**Comment by eCrimeLabs** [comment]
Hey @Rafiot I've now tried both and the object relation/reference is not being added. 

Added the "standalone=False" on both object creations

**Comment by adulau** [comment]
Indeed, we had a bug in MISP ;-) This has been fixed in https://github.com/MISP/MISP/commit/6db77bb862d083acc0f5cf1298e6e4df0acfa4f7 could you test if this is fixed for you? Thanks a lot.

**Comment by eCrimeLabs** [comment]
I can confirm that it work perfect :)

Thanks a bunch and happy new year :)

**Comment by adulau** [comment]
Thanks a lot for the feedback! All the best for you and your family.
