### ISSUE TITLE
Remove old examples

### ISSUE THREAD

**Issue by ninoseki** [MISP/PyMISP#530]
IMHO it's good to remove examples which use deprecated methods.
Those examples are obstacles to learn how to use PyMISP in the latest manner.

**Comment by Rafiot** [comment]
Absolutely, you're right, I'll try to do that in the coming days.

If you find broken examples, do not hesitate to do a PR to remove them.

**Comment by cudeso** [comment]
Hi, instead of removing the examples that rely on deprecated methods, maybe it would have made more sense to move them to a directory "examples_deprecated"? 

Someone who is still interested in the 'logic' of the old examples can then transform them to the new methods. Now this is fairly impossible/difficult besides going through the Github commit history.

**Comment by Rafiot** [comment]
we did some cleanup/update in the directory, closing for now.
