### ISSUE TITLE
Struggling with update_attribute

### ISSUE THREAD

**Issue by sustefil** [MISP/PyMISP#532]
Hi all, I am struggling with the method update_attribute. It does not work as expected.
Basically I need to filter for attributes' specific tags and add/edit them.

The corresponding method for event works, but not for attribute, see below:

```
# This works fine
m = pymisp.ExpandedPyMISP(misp_test_endpoint, misp_test_api_key, ssl=False)

ev = m.get_event(event=45, pythonify=True)
ev.add_attribute('ip-dst', '10.20.30.40')

m.update_event(ev)

----------------------------------------------------------------------------------------
# This does not work, although the update finishes successfully with 200
test_attr = ev.attributes[0]
test_attr.add_tag('This tag wont show in MISP')

m.update_attribute(test_attr)
```

Seems that this request can not really update attribute's tags?
https://github.com/MISP/PyMISP/blob/master/pymisp/api.py#L424

Thanks for help!

I am using PyMISP 2.4.120 and MISP 2.4.119

**Comment by Rafiot** [comment]
Two things to check here:
* does the tag exist on the platform?
* if not, is your user allowed to create tags? If it is not, the tag is silently discarded by MISP.

**Comment by sustefil** [comment]
> Two things to check here:
> 
> * does the tag exist on the platform?
> * if not, is your user allowed to create tags? If it is not, the tag is silently discarded by MISP.

1) Yes (tried both existing and non-existing tags)
2) Yes, I use the admin user

Still doesn't work..

Btw this method successfully adds the tag 'name' (just a silly test to prove I can add tags to attributes):
`x = ev.add_attribute('domain', 'test.info', **{'Tag': {'name': 'admin_only'}})`

**Comment by Rafiot** [comment]
Right, I know what 's going on, it is a limitation on MISP code side: update event will automatically go through every part of the JSON document, and update everything it can. Update attribute doesn't do that.

In your case, the slightly lighter approach than POSTing the whole event is to use the `tag` method in PyMISP, it is a lightweight way to add a tag to an event or an attribute.

I described the issue here for reference: https://github.com/MISP/MISP/issues/5576

**Comment by sustefil** [comment]
Ok thanks,

I am now successfully using the `tag` method, I also need to edit the `comment`. Currently I have this solution, but it is a lot of requests per attribute, do you think I can do it more efficiently? (shall I wait for the update_attribute method fix?)

```
for attr_uuid, f3_data in f3_results.items():
    misp.tag(attr_uuid, f'f3-score-ip={f3_data["ip"][0]}')
    misp.tag(attr_uuid, f'f3-score-domain={f3_data["domain"][0]}')

    misp.untag(attr_uuid, 'No f3 score yet')

    temp_attr = misp.get_attribute(attr_uuid)
    temp_attr['Attribute']['comment'] += '; TEST'

    # without this line, it fails with error: 'Attribute could not be saved: Attribute in the request
    not newer than the local copy'. I found this workaround in issue 269
    temp_attr['Attribute']['timestamp'] = int(time() + 1)
    
    misp.update_attribute(temp_attr)
```

**Comment by Rafiot** [comment]
In your case, I'd update all the the events locally (look at `pythonify=True` to get `MISPEvent`  objects instead of JSON blobs, it will be way easier to manage), and then POST each event with the `update_event` method. 
If the ratio of updated attribute vs. non-updated attributes in low, you can also reinitialize the list of attributes in the `MISPEvent`, only re-add the updated ones in it, and post the `MISPEvent`. This way, you will do one single call, with your list of updated attributes, and it will be just fine (the existing, non-updated attributes, won't be touched nor deleted).

Note that the tags will only be added, and none of them deleted. In order to untag an attribute, you still need to call `untag` sequentially.

I'd recommend you not to wait https://github.com/MISP/MISP/issues/5576, because it will take a while.

**Comment by sustefil** [comment]
Nice, thanks for suggestions, closing the issue
