### ISSUE TITLE
Analysis field should be string, not integer

### ISSUE THREAD

**Issue by dronnix** [MISP/PyMISP#535]
Hi!

According to [specification](https://github.com/MISP/misp-rfc/blob/master/misp-core-format/raw.md#manifest) analysis has a string type, not an integer. However, in some places (like [this](https://github.com/MISP/PyMISP/blob/85b4f1d05178bdaa601fb63aff457f0221923be8/pymisp/mispevent.py#L970) ) it filled with an integer value. Affects generating feeds.

Thanks.

**Comment by Rafiot** [comment]
Hi, 

MISP accepts integer and string for every field, and does the conversion itself. Can you send an example that is causing a issue?

**Comment by dronnix** [comment]
Sure, it can be reproduced with [feed-generator](https://github.com/MISP/PyMISP/blob/master/examples/feed-generator/generate.py) from example.

**Comment by Rafiot** [comment]
Yes, but MISP can import it, so it should (?) not be a problem. And if it is, can you give us more details on what's not working, please?

**Comment by dronnix** [comment]
MISP itself is OK.  I have a problem with third-party MISP feed importer, that expects string (according to MISP RFC), but got an integer.

**Comment by Rafiot** [comment]
I'm very curious about that 3rd party importer. Is it something publicly available somewhere? Because I feel like there will be other problems if it fails on that.

**Comment by dronnix** [comment]
> Is it something publicly available somewhere?

Not, yet :disappointed:  It's a part of proprietary system, written in Go. Maybe the importer will be opensourced later. 

> Because I feel like there will be other problems if it fails on that.

You are right. Have finished experiments, and see that some other fields have wrong (according to RFC) type. Could You please recommend some other MISP generator?  May be You know, what generator is used for https://www.circl.lu/doc/misp/feed-osint?  It works fine.

**Comment by Rafiot** [comment]
This one is generated by the same code.

We should adapt the RFC, because it will make way more sense. In the meantime, can you list all the bits that are failing? the fee generator in PyMISP is the default implementation, so using it wil always work.

**Comment by sevlyar** [comment]
Hi!

@Rafiot, the RFC change will break backward compatibility: some existing consumers (written on strongly-typed language) doesn't expect that the field contains integer and they will fail.

**Comment by iglocska** [comment]
Yeah, not a fan of changing the RFC, let's keep that as it is. However, that doesn't mean that tools can't be more lenient.

**Comment by Rafiot** [comment]
Okay, so let me know if we should change that in PyMISP or not, I don't really care.

But be sure that PyMISP will keep being as pythonic as possible, so I'll keep converting everything that is integer to the proper type to make it as easy to use as possible for the users or the API.

My thinking is that the validator you're using should not enforce integer <-> string typing, because it doesn't make much sense.

**Comment by sevlyar** [comment]
But an implementation must comply with specifications. If i specify a contract and then break it by myself, who does trust me?

Let me suggest a solution. To not change current behaviour of PyMISP, it is possible to implement an optional flag which forces the tool to follow the specification. The tool will generate strings instead of numbers in 'analysis' field when the flag is turned on.

**Comment by Rafiot** [comment]
Should be fixed. It will be in the next release, and if you want to play with it in the meantime, use the master branch.

And if you could publish the validator, that would be awesome.

**Comment by dronnix** [comment]
Thanks a lot!
