### ISSUE TITLE
Should a FileObject be standalone ?

### ISSUE THREAD

**Issue by ldbo** [MISP/PyMISP#593]
The constructor of `tools.fileobject.FileObject` uses the default value `True` for `standalone`, which prevents the user from using `FileObject.add_reference` to add a reference to another object. A workaround is to use `PyMISP.add_object_reference`, but this is less convenient.

Is there any particular reason for `FileObject` to be standalone ?

**Comment by Rafiot** [comment]
Yes, all the objects are standalone by default. References will only be added to an event in the two following situations:
* after the referrer and the referee have been added to the event
* you push a complete MISPEvent with all the references.

The reason we default to standalone is because it correspond with what happen in practice when you push standalone objects to MISP: unless all the objects are pushed first and only afterwards the references, the references will be discarded.

**Comment by ldbo** [comment]
Thank you for your quick reply ! Then, why is MISPObject not standalone by default ?

**Comment by Rafiot** [comment]
because generally, a MISPObject is added in a MISPEvent... I should probably normalize it all the way, and probably to `standalone=False` with a helper that try to attach the references, and returns a warning if there is an issue.
