### ISSUE TITLE
Suppress warnings

### ISSUE THREAD

**Issue by gsonetic** [MISP/PyMISP#615]
I'm getting a warning when adding an attribute which does'nt have an object relation:
WARNING [mispevent.py:xx - add_attribute() ] The template (xxx) doesn't have the object_relation (xxx) you're trying to add.

Debug=False does'nt suppress warnings.

**Comment by Rafiot** [comment]
Yes, it is not a debug message, but an actual warning: it means that the template you're using has a relation missing. It is most probably something you want to avoid, as it means that you do not add to the object everything you want to.

If you really don't care, and are sure you want to get rid of it, you can do as described here:
https://www.tutorialspoint.com/How-to-disable-logging-from-imported-modules-in-Python

with `CRITICAL` instead of `WARNING`

**Comment by lsethi25** [comment]
Hello,
Even I am getting the same warning but only in some cases.
I wanted to know how to fix this.

**Comment by Rafiot** [comment]
yes, it is explained in the link above.

**Comment by lsethi25** [comment]
> yes, it is explained in the link above.

Hi, I meant I want to actually fix the issue.

**Comment by Rafiot** [comment]
It depends on the object template you're using: https://github.com/MISP/PyMISP/blob/main/pymisp/mispevent.py#L945

So without a code snippet and the template, I cannot really tell you more. If you need more help, please open a new issue.
