### ISSUE TITLE
Reportlab generator: Pretends to be optional, but is not

### ISSUE THREAD

**Issue by wagner-certat** [MISP/PyMISP#703]
https://github.com/MISP/PyMISP/blob/6aab2717e22a823c93725a06b08f7dd3468fc9db/pymisp/tools/reportlab_generator.py#L21-L37

Looks like reportlab is optional. But then:

https://github.com/MISP/PyMISP/blob/6aab2717e22a823c93725a06b08f7dd3468fc9db/pymisp/tools/reportlab_generator.py#L52

a name is used which needs to be imported in line 29

**Comment by Rafiot** [comment]
Right, you're technically correct, someone trying to import anything in this class and missing reportlab should get an ImportError exception telling them to install reportlab, 

I'll fix that soon.

Out of curiosity, how did you trigger it? Because unless you manually go load something in the module, it's not imported by anything anywhere.

**Comment by wagner-certat** [comment]
> Right, you're technically correct, someone trying to import anything in this class and missing reportlab should get an ImportError exception telling them to install reportlab,

Where is that ImportError raised?

> I'll fix that soon.

Thanks!

> Out of curiosity, how did you trigger it?

Running the tests without having reportlab installed.

**Comment by Rafiot** [comment]
That should be fixed: https://github.com/MISP/PyMISP/commit/a2d7cbd7632da23cb0816fa0b041b939d4d520b6
