### ISSUE TITLE
Unexpected search behavior when the value is set to '0' or consists of spaces.

### ISSUE THREAD

**Issue by AnastasiiaRozlyvan** [MISP/PyMISP#734]
I use search to find events containing an attribute whose value exactly matches the search value. Here is a code spinet of how I use it:
```python
misp = PyMISP(
            key='mykey',
            url='myinstance',
            ssl=False
        )
events = misp.search(
    value='somevalue', metadata=False
)
```

However, I noticed that if I set value to '0'  or to several spaces, then I get a huge amount of data, although I am sure that there are no events matching this criterion. 
Could you please tell me if this is a bug or expected behavior? Perhaps I misunderstand the search logic?
My pymisp version is 2.4.141.1

**Comment by Rafiot** [comment]
The search will return by default a list of events (in your case only the metadata of said events), and you will get all the events with at least one attribute matching your query, so it can be pretty big. If you're specifically searching for attributes, you can pass the key `controller="attributes"`, and it will only return the attributes matching your query (instead of the events)

So if you're serching for "0", it's going to match a vast amount of data. Searching for several spaces will be stripped and search for the empty string, which in turns will return the complete database. Is there any reason you're doing that? It might be a but if you have a good usecase, but I wouldn't consider it a valid query otherwise.

**Comment by AnastasiiaRozlyvan** [comment]
Thanks for the answer! I understood about spaces, now it's clear why it works like that. But still not clear about 0. Does this search return events containing an attribute that exactly matches the search value, or does it search substrings? 

This is not some special usecase, we are working on integration with misp and want to check all possible options that may crash our application.

**Comment by Rafiot** [comment]
It won't search on substring by default (`%foo%` will search for `foo` anywhere in the value). But if you search for `0` as an integer, it will probably be checked as `False` somewhere in the query and will do the same as am empty query.

I'd suggest to check against such query in your integration, but also to use pagination (`limit` and `page` keys), to avoid legitimate, but huge, responses.

**Comment by AnastasiiaRozlyvan** [comment]
Thank you very much for your advice!
