### ISSUE TITLE
Confusing typing of searchall in pymisp.search

### ISSUE THREAD

**Issue by Gramet** [MISP/PyMISP#788]
Hi there,

I just noticed that the type of the `searchall` parameter in the PyMISP.search (https://pymisp.readthedocs.io/en/latest/modules.html#search) function is hinted to be **Optional[bool]**, however the `/{controller}/restSearch` endpoint (which is called in the background) expects `searchall` as a **string**.

I guess the latter is the expected behavior, as I have been successfully feeding string values through this parameter, but I just wanted to point it out in case it needs to be fixed. :)

**Comment by Rafiot** [comment]
Hey, yes, we do that quite often where we use python types when it makes more sense, and convert it internally. It is generally easier for the user of the module than stick to the types expected by MISP (which is going to be string, most of the time).

If it's an issue, please let me know, but otherwise, I'll close this issue.
