### ISSUE TITLE
why doesn't misp.search_index(publish=False) return events with zero attributes?

### ISSUE THREAD

**Issue by github-germ** [MISP/PyMISP#847]
We've noticed that `search_index` does not include events with zero attributes in the result.
```
 eventList = misp.search_index(
        published = False,
        pythonify = False,
        minimal   = True)
```
Is there another method to retrieve those. We use these type of queries to detect opportunities of data mitigation.

Thanks.

**Comment by tomking2** [comment]
This appears to be intentional @github-germ, see /api/openapi#operation/searchEvents on your respective MISP instance. The use of the `minimal` parameter set to True explicitly states only events with attribute count > 0 is shown. In order to return events with 0 attributes, removing the `minimal` parameter should do the trick.

![image](https://user-images.githubusercontent.com/15731689/189954541-c74fc8d0-cc3a-4859-99cb-cff603de81bf.png)

**Comment by github-germ** [comment]
@tomking2 -- Thanks! Works well.
