### ISSUE TITLE
misp.search dataframe comparison

### ISSUE THREAD

**Issue by bobhes** [MISP/PyMISP#896]
```
def readZeekFileJson(filename):
    df = pd.read_json(filename, lines=True)
    return df

def isinMisp(df):
    for index, row in df.iterrows():
        if (df['id.resp_h']) in mispData:
            return print(True)
    return print(False)
if __name__ == '__main__':

    filename = sys.argv[1]
    df = readZeekFileJson(filename)
    misp = ExpandedPyMISP(misp_url, misp_key, misp_verifycert, debug=True)
    misp_types = ('ip-dst', 'ip-src')

# use value? attribute?
    mispData = misp.search(publish_timestamp='30d',pythonify=False, type_attributes=misp_types)

df = readZeekFileJson(filename)
    filterdf(df)
    isinMisp(df)
```
I'm trying to compare a dataframe filled with ip adresses -> ip.resp_h with the misp database. This code doesn't work. How do I compare multiple ip adresses in a dataframe with the misp database?

**Comment by bobhes** [comment]
when there is a ip adress of the dataframe in the misp database. I want it to search for the corresponding event

**Comment by Rafiot** [comment]
I'm not sure what the dataframe is, nor where it comes from, but the search query you're running on MISP is incorrect: `type_attributes` doesn't exists (it should be `type_attribute`), and `type_attribute` only accepts one type.

Then, the query you're running will return complete MISP events published in the last 30 days that contain at least one attribute of that type. You *might* want to pass `controller='attributes'` in order to reduce the amount of data you're getting back. And besides that, you probably want to check if the IP from the dataframe is a value in the list of responses from MISP, instead of against a complete json dump.

**Comment by Rafiot** [comment]
okay, and does it works? Also, `return print(True)` is not what you want. You want to either return True, or print it.
