### ISSUE TITLE
FIlter attributes based on date doesn't work.

### ISSUE THREAD

**Issue by Dystopie-github** [MISP/PyMISP#933]
Hello,

I use to have a working 1 line to filter attribute by date (misp v165). Since the latest update, none of the filter seems to work. It still return result but I get 44Mb of data. I can't open that file. I know I have ~50 events without attach files every day.

Here the line / options I try with the same result. 

result = misp.search('attributes', to_ids=1, type_attribute=["ip-dst"], date_from="2023-02-19", date_to=date, published=true)
result = misp.search('attributes', to_ids=1, type_attribute=["ip-dst"], date_from="2023-02-19", published=true)
result = misp.search('attributes', to_ids=1, type_attribute=["ip-dst"], publish_timestamp=1676920828)

`
date_epoch_start = today - timedelta(days=1)
date_epoch_start = str(date_epoch_start) + " 04:58:00"  
date_epoch_start = datetime.strptime(date_epoch_start, "%Y-%m-%d %H:%M:%S").timestamp()  
#I tried multiple type for date_epoch_start; int, str or no convertion.  
result = misp.search('attributes', to_ids=1, type_attribute=["ip-dst"], publish_timestamp=(str(int(date_epoch_start))))  
`

The next one return 58Mb
result = misp.search('attributes', to_ids=1, type_attribute=["ip-dst"], from_="2023-02-19", published="true")

I run out of idea on how to use the filter with the latest version.

I am expecting to get list of attributes publish since the last 24 hours.

**Comment by Rafiot** [comment]
`from_` is not an expected parameter, so that very last request will most probably return the whole database. It should be `date_from`, I guess (?)

We're not aware of a breaking change on PyMISP or MISP regarding the search query between v165 and v168 so the issue is somewhat weird. And the tests are passing so it is not a but we have on the test system.

Two questions for you to check on your system:
* Is the date on the machine correct?
* Even with only ~50 events in 24h, the json returned might be pretty big. Have you checked the attributes you're getting aren't matching the search query? In order to get a smaller set of attributes in the response, you can paginate (with the keys `limit` and `page`)

**Comment by Dystopie-github** [comment]
It a mistake on my side. I have another script to publish event if they are not publish. 

I was using 
result = misp.search('attributes', to_ids=1, type_attribute=["ip-dst", "domain"], date_from="2022-03-14", date_to=date, published=False)

Instead of published=0 which lead to all my events to have a publish date of today. 

We can close this ticket.  Thank you and sorry

**Comment by Rafiot** [comment]
No problem, thank you for the update!
